routes/web.php
<?php
use App\Http\Controllers\Admin\Auth\AuthController;

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ActualPaymentController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\FeedbackController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\PaymentLogController;
use App\Http\Controllers\Admin\ReminderNotificationController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ActivityController;
use App\Http\Controllers\Admin\UserActivityProgressBreakdownController;
use App\Http\Controllers\Admin\UserDiscussionController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\Auth\RegisteredUserController;
use App\Http\Controllers\Admin\UserActivityController;



use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
    Route::get('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store'])->name('registerAdmin')->middleware('guest');            
    Route::get('send-password-recovery-code/{email}', [UserController::class, 'sendPasswordRecoveryCode']);
    Route::get('check-password-recovery-code/{email}/{code}', [UserController::class, 'checkPasswordRecoveryCode']);
    Route::post('update-password-recover', [UserController::class, 'passwordRecover'])->name('passwordRecover');
    Route::get('check-email/{email}', [UserController::class, 'checkEmail'])->name('checkEmail');

});


Route::group(['middleware' => 'prevent-back-history'],function(){

    Route::group(['middleware' => 'auth'], function () {
        Route::prefix('admin')->group(function () {
        
            Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index')->name('dashboard');
            Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
            //agent
            Route::get('agents', [UserController::class, 'agents'])->name('agents.index');
            Route::get('inactive-agents', [UserController::class, 'inActiveAgents'])->name('inActiveAgents');
            Route::get('register-agents', [UserController::class, 'viewRegisterAgent'])->name('getRegisterAgent');
            Route::post('do-register-agents', [UserController::class, 'registerAgent'])->name('registerAgent');
            Route::post('agent-inactive', [UserController::class, 'deActivateUser']);
            Route::get('agent-profile/{id}', [UserController::class, 'agentProfile'])->name('agentProfile');
            Route::get('agent-edit-profile/{id}', [UserController::class, 'agentEditProfile'])->name('agentEditProfile');
            Route::post('agent-update-profile', [UserController::class, 'agentUpdateProfile'])->name('agentUpdateProfile');
            Route::get('view-assigned-activities/{id}', [ActivityController::class, 'viewAssignedActivities'])->name('viewAssignedActivities');
            Route::get('assigned-task-details/{id}', [ActivityController::class, 'assignedTasksDetails'])->name('assignedTasksDetails');
            Route::get('view-monthly-progress/{agentId}', [UserActivityController::class, 'viewMonthlyProgress'])->name('viewMonthlyProgress');
            Route::get('user-discussion/{agentId}', [UserDiscussionController::class, 'discussionBoard'])->name('discussionBoard');
            Route::post('add-discussion', [UserDiscussionController::class, 'addDiscussion'])->name('addDiscussion');

            
            //manager
            Route::get('managers', [UserController::class, 'managers'])->name('managers.index');
            Route::get('recieved-request-details/{managerId}',  [UserController::class, 'recievedRequestDetails'])->name('recievedRequestDetails');
            Route::post('reject-managers-request',  [UserController::class, 'rejectManagersRequest'])->name('rejectManagersRequest');
            Route::get('rejected-manager-details/{managerId}',  [UserController::class, 'rejectedRequestDetails'])->name('rejectedRequestDetails');

             
            //activity management
            Route::get('activity-management', [ActivityController::class, 'index'])->name('activity.management.index');
            Route::post('assign-agent-activity', [ActivityController::class, 'assignAgentActivity'])->name('assignAgentActivity');
            Route::post('find-activity-by-id', [ActivityController::class, 'findActivitiesByCatId']);
            Route::get('create-activity-management', [ActivityController::class, 'createActivityManagement'])->name('createActivityManagement');   
            
            //category management
            Route::get('category-management', [CategoryController::class, 'index'])->name('category.index');
            
            //payment
            Route::get('payment-log', [ActualPaymentController::class, 'index'])->name('payment.index');
            Route::get('settings', [SettingController::class, 'index'])->name('settings.index');
            Route::get('feedback', [FeedbackController::class, 'index'])->name('feedback.index');


            //profile
            Route::get('my-profile', [UserController::class, 'myProfile'])->name('myProfile');
            Route::get('my-profile-edit', [UserController::class, 'myProfileEdit'])->name('myProfileEdit');
            Route::post('update-my-profile', [UserController::class, 'updateMyProfile'])->name('updateProfile');

            Route::post('password-change', [UserController::class, 'changePassword'])->name('passwordChange');
            Route::get('my-notifications', [NotificationController::class, 'getMyNotifications'])->name('myNotificaions');
            Route::get('feedback-detail-manager/{id}', [FeedbackController::class, 'feedbackDetailsManager'])->name('feedbackDetailsManager');
            Route::get('feedback-detail-agent/{id}', [FeedbackController::class, 'feedbackDetailsAgent'])->name('feedbackDetailsAgent');
            Route::get('delete-feedback/{id}', [FeedbackController::class, 'deleteFeedback'])->name('deleteFeedback');
            Route::get('edit-settings',  [SettingController::class, 'editSettings'])->name('editSettings');
            Route::post('update-settings',  [SettingController::class, 'updateSettings'])->name('updateSettings');
            Route::post('add-category', [CategoryController::class, 'addCategory'])->name('addCategory');
            Route::post('add-activity', [ActivityController::class, 'addActivity'])->name('addActivity');
            Route::post('update-category', [CategoryController::class, 'updateCategory'])->name('updateCategory');
            Route::post('update-activity', [ActivityController::class, 'updateActivity'])->name('updateActivity');
            Route::post('update-user-status', [UserController::class, 'updateUserStatus'])->name('updateUserStatus');
            Route::get('manager-profile/{id}', [UserController::class, 'managerProfile'])->name('managerProfile');
            Route::get('manager-edit-profile/{id}', [UserController::class, 'managerEditProfile'])->name('managerEditProfile');
            Route::post('manager-update-profile', [UserController::class, 'managerUpdateProfile'])->name('managerUpdateProfile');
            Route::get('managers-requests', [UserController::class, 'managersRequests'])->name('managersRequests');
            Route::get('inactive-managers', [UserController::class, 'inActiveManagers'])->name('inActiveManagers');
            Route::get('create-manager', [UserController::class, 'createManager'])->name('createManager');
            Route::post('add-manager', [UserController::class, 'addManager'])->name('addManager');
            Route::get('view-assigned-agents/{id}', [UserController::class, 'viewAssignedAgents'])->name('viewAssignedAgents');
            Route::get('get-activity-by-category/{id}', [ActivityController::class, 'getActivitiesByCatId'])->name('getActivitiesByCatId');

            Route::post('add-reminder', [ReminderNotificationController::class, 'addReminder'])->name('addReminder');

            
        });
    });    
});    

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //define constants here
    const CATEGORY_STATUS_ACTIVE    = "1";
    const CATEGORY_STATUS_INACTIVE  = "0";


    use HasFactory;
    protected $fillable = [
        'name', 'status'
    ];
    public function getAllCategories($limit, $offset){
        $cats =  Category::where('status', self::CATEGORY_STATUS_ACTIVE)->orderBy('id', 'DESC');
        $count = count($cats->get());
        $cats = $cats->limit($limit)->offset($offset)->orderBy('id', 'DESC')->get();
        return array('data' => $cats, 'count'=> $count);

    }
    public function getCreatedAtAttribute($dateTime)
    {
        $date = $this->asDateTime($dateTime);
        return $date->timezone(auth()->user()->timezone)->toDateTimeString();
    }
}

resources/views/admin/category-management-noData.blade.php
@extends('admin.layout.app')
@section('title', __('Agents'))
@section('content')

<div class="app-content content dashboard">
    <div class="content-wrapper">
        <div class="content-body">
            <!-- Basic form layout section start -->
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card ">
                            <div class="card-content collapse show">
                                <div class="card-dashboard">
                                    <div class="row">
                                        <div class="col-12">
                                            <h1 class="mb-2">CATEGORY MANAGEMENT</h1>
                                        </div>
                                    </div>
                                    <div class="text-md-right text-center">
                                        <a data-toggle="modal" data-target=".addCategoryModal" class="site-btn blue mb-1">ADD NEW</a>
                                    </div>
                                    <div class="empty-div">
                                        <h1>No Data Found</h1>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>



<!-- Add Category Modal -->
<div class="modal fade addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content site-modal">
            <i class="fas fa-times close modal-close" data-dismiss="modal" aria-label="Close"></i>
            <p class="modal-heading text-center">Add Category</p>
            <div class="row">
                <div class="col-12">
                    <div class="form-field">
                        <label for="" class="site-label">Category Name*</label>
                        <input type="text" class="site-input" placeholder="Enter Category Name">
                    </div>
                </div>
            </div>
            <div class="text-center mt-2">
                <a href="#" class="site-btn blue">Add</a>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/discussion-board-nomessage.blade.php
@extends('admin.layout.app')
@section('title', __('Discussion board no message'))
@section('content')

<div class="app-content content dashboard">
    <div class="content-wrapper">
        <div class="content-body">
            <!-- Basic form layout section start -->
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card ">
                            <div class="card-content collapse show">
                                <div class="card-dashboard">
                                    <div class="row">
                                        <div class="col-12">
                                            <h1 class="mb-2"><a href="agents.php"><i class="fas fa-chevron-left mr-1"></i> AGENTS</a></h1>
                                        </div>
                                    </div>

                                    <div class="custom-card">
                                        <div class="card-heading">
                                            <p>discussion board</p>
                                        </div>
                                        <div class="card-area board">
                                            <div class="profile-picture-div">
                                                    <img src="./images/img-placeholder.png" class="profile-pic img-fluid" alt="">
                                                    <p class="form-heading pt-1 mb-0">001</p>
                                                    <p class="form-heading">John Smith</p>

                                                    <!-- <label for="picture">
                                                        <i class="fas fa-camera profile-pic-icon"></i>
                                                    </label>
                                                        <form style="display: none;">
                                                        <input type="file" name="pic" accept=".gif,.jpg,.png,.tif|image/*" id="picture">
                                                        <input type="submit">
                                                    </form> -->
                                            </div>
                                            <!-- <p class="form-heading pt-1 mb-3">Personal Information</p> -->
                                            <p class="form-heading pt-1 mb-2">No Message Found</p>
                                            <div class="form-field">
                                                <textarea class="site-input" name="" id="" cols="30" rows="10" placeholder="Write Something Here"></textarea>
                                                <a href="#" class="site-btn blue mt-1">SEND</a>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>


<!-- Register Agent Modal -->
<div class="modal fade registerAgent" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content site-modal">
            <i class="fas fa-times close modal-close" data-dismiss="modal" aria-label="Close"></i>
            <div class="text-center">
                <div class="modal-icon-div">
                    <i class="fas fa-ban modal-icon"></i>
                </div>
                <p class="modal-heading">System Message</p>
                <p class="modal-text">Are you sure you want to register this agent's?</p>
                <div class="modal-btn-div">
                    <a class="site-btn orange" id="yesregister">Yes</a>
                    <a class="site-btn blue" data-dismiss="modal" aria-label="Close">No</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Register Agent Confirmation -->
<div class="modal fade yesregisterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content site-modal">
            <i class="fas fa-times close modal-close" data-dismiss="modal" aria-label="Close"></i>
            <div class="text-center">
                <div class="modal-icon-div">
                    <i class="fas fa-ban modal-icon"></i>
                </div>
                <p class="modal-heading">System Message</p>
                <p class="modal-text">Agent has been registered successfully</p>
                <div class="modal-btn-div">
                    <a class="site-btn blue" data-dismiss="modal" aria-label="Close">GOT IT</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/feedback-details-manager.blade.php
<?php 
$title = 'Feedback';
$pg = 'feedback';
$authUser = Auth()->user();
?>
@extends('admin.layout.app')
@section('title', __('Feedback detail manager'))
@section('content')
<?php $notificationService = app('App\Services\NotificationService'); ?>

<div class="app-content content dashboard">
    <div class="content-wrapper">
        <div class="content-body">
            <!-- Basic form layout section start -->
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card ">
                            <div class="card-content collapse show">
                                <div class="card-dashboard">
                                    <div class="row">
                                        <div class="col-12">
                                            <h1 class="mb-2"><a href="{{route('feedback.index')}}"><i class="fas fa-chevron-left mr-1"></i> FEEDBACK DETAILS</a></h1>
                                        </div>
                                    </div>
                                    <div class="custom-card">
                                        <div class="card-heading">
                                            <p>feeback</p>
                                            <p>manager id:{{$data[0]->user_id}}001</p>
                                        </div>
                                        <div class="card-area">
                                            <div class="text-md-right text-left">
                                                <p class="form-heading mb-0">Registration Date :</p>
                                                <p><?php echo $dtime =  $notificationService::dateTimeFormat($data[0]->created_at);?></p>

                                            </div>
                                            <div class="profile-picture-div">
                                                @if($data[0]->profile_image)
                                                        <img src="{{asset('assets/admin/images/')}}{{'/'}}{{$data[0]->profile_image}}" class="profile-pic img-fluid" alt="avatar"> 
                                                    @else
                                                        <img src="{{asset('assets/admin/images/img-placeholder.png')}}"  class="profile-pic img-fluid" alt="avatar"> 
                                                    @endif
                                        
                                            </div>
                                            <!-- <p class="form-heading pt-1 mb-3">Personal Information</p> -->
                                            <div class="row">
                                                <div class="col-md-6 col-12">
                                                    <div class="form-field">
                                                        <label for="" class="site-label">First Name*</label>
                                                        <input type="text" class="site-input" value="{{$data[0]->first_name}}" readonly>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-12">
                                                    <div class="form-field">
                                                        <label for="" class="site-label">Last Name*</label>
                                                        <input type="text" class="site-input"  value="{{$data[0]->last_name}}" readonly>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-12">
                                                    <div class="form-field">
                                                        <label for="" class="site-label">Email*</label>
                                                        <input type="email" class="site-input" value="{{$data[0]->email}}" readonly>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-12">
                                                    <div class="form-field">
                                                        <label for="" class="site-label">Subject*</label>
                                                        <input type="text" class="site-input" value="{{$data[0]->subject}}" readonly>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-field">
                                                        <label for="" class="site-label">Address*</label>
                                                        <input type="text" class="site-input" value="{{$data[0]->address}} {{$data[0]->city}} {{$data[0]->state}} {{$data[0]->country}}" readonly>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@endsection

resources/views/admin/view-assigned-agents.blade.php
<?php 
$title = 'Managers management';
$pg = 'managers';
?>

@extends('admin.layout.app')
@section('title', __('View assigned agents'))
@section('content')
<?php $notificationService = app('App\Services\NotificationService'); ?>
<div class="app-content content dashboard">
    <div class="content-wrapper">
        <div class="content-body">
            <!-- Basic form layout section start -->
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card ">
                            <div class="card-content collapse show">
                                <div class="card-dashboard">
                                    <div class="row">
                                        <div class="col-12">
                                            <h1 class="mb-2"><a href="{{route('managers.index')}}"><i class="fas fa-chevron-left mr-1"></i> MANAGERS</a></h1>
                                        </div>
                                    </div>
                                    <div class="profile-picture-div pb-4">
                                    @if($data['managerData']->profile_image)
                                    <?php $img =  $data['managerData']->profile_image; ?>
                                                        <img src="{{asset('assets/admin/images/')}}{{'/'}}{{$img}}" class="profile-pic img-fluid" alt="">
                                                    @else
                                                        <img src="{{asset('assets/admin/images/img-placeholder.png')}}" class="profile-pic img-fluid" alt="">
                                                    @endif

                                        <p class="form-heading pt-1 mb-0">Manager ID : {{$data['managerData']->id}}</p>
                                        <p class="form-heading">Manager Name :{{$data['managerData']->first_name}}{{' '}}{{$data['managerData']->last_name}}</p>
                                    </div>
                                    <p class="form-heading pl-1 mb-2">Agent Log</p>
                                    <div class="row ml-0 mr-0 align-items-end">
                                                <div class="col-12">
                                                    <label  for="">Sort By:</label>
                                                </div>
                                                <div class="col-xl-2 col-lg-6 col-12">
                                                    <label  for="">From:</label>
                                                    <input id="datepicker-1" class="site-input border" type="text" readonly>
                                                </div>
                                                <div class="col-xl-2 col-lg-6 col-12">
                                                    <label  for="">To:</label>
                                                    <input id="datepicker-2" class="site-input border" type="text" readonly>
                                                </div>
                                                <div class="col-xl-2 col-lg-6 col-12">
                                                    <a href="block-users.html" class="site-btn orange mb-1">APPLY/CLEAR</a>
                                                </div>
                                                <!-- <div class="col-xl-8 col-lg-6 col-12 text-md-right">
                                                    <div class="btn-with-filter">
                                                        <a href="block-users.html" class="site-btn green">BLOCK USERS</a>
                                                        <select name="" id="" class="filter-select mb-0">
                                                            <option value="">Filter by Status</option>
                                                            <option value="">Select 1</option>
                                                            <option value="">Select 2</option>
                                                        </select>
                                                    </div>
                                                </div> -->
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="maain-tabble table-responsive">
                                                <table class="table table-striped table-bordered zero-configuration">
                                                    <thead>
                                                        <tr>
                                                            <th>S.NO</th>
                                                            <th>AGENT ID</th>
                                                            <th>AGENT NAME</th>
                                                            <th>REGISTRATION DATE</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    @if(count($data['agentsData']))
                                                    <?php $i = 0; ?>
                                                    @foreach($data['agentsData'] as $agent)
                                                        <tr>
                                                            <td>{{$i}}</td>
                                                            <td>{{$agent->id}}</td>
                                                            <td>{{$agent->first_name}} {{' '}} {{$agent->last_name}}</td>
                                                            <td><?php echo $dtime =  $notificationService::dateTimeFormat($agent->created_at);?></td>                                                        
                                                            </tr>
                                                    <?php $i++; ?>
                                                    @endforeach
                                                    @endif
                                                    </tbody>
                                                </table>
                                            </div> 

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

@endsection